"use client";

import { useMemo, useState } from "react";
import {
  Activity, ArrowRight, BarChart3, Bell, Boxes, Building2, Check, ChevronDown, ChevronRight,
  CircleDollarSign, Clock3, Command, FileCheck2, FileText, Gauge, Grid2X2, HandCoins, History,
  KeyRound, Layers3, Link2, Map, MapPin, Menu, MessageSquareText, PackageCheck, PanelLeftClose,
  Plus, QrCode, Route, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Truck,
  UserRoundCheck, UsersRound, WalletCards, Webhook, X,
} from "lucide-react";
import { deliveries, intelligence, priceRules, transactions, type Delivery } from "@/lib/data";
import { Badge, Button, Card, CardHeader, ComingSoon, Metric, StatusBadge } from "@/components/ui";

type Role = "Operasyon" | "Şirket" | "Kurye" | "Yönetici";
type View = "command" | "deliveries" | "company" | "courier" | "pricing" | "finance" | "intelligence" | "integrations" | "security";

const roleViews: Record<Role, View> = { Operasyon: "command", Şirket: "company", Kurye: "courier", Yönetici: "intelligence" };

const nav = [
  { group: "PAZARYERİ", items: [
    { id: "command", label: "Operasyon Merkezi", icon: Command },
    { id: "deliveries", label: "Canlı Teslimatlar", icon: Route, count: "24" },
    { id: "company", label: "Şirket İşlemleri", icon: Building2 },
    { id: "courier", label: "Kurye Pazaryeri", icon: Truck },
  ]},
  { group: "YÖNETİM", items: [
    { id: "pricing", label: "Fiyatlandırma", icon: SlidersHorizontal },
    { id: "finance", label: "Finans & Mutabakat", icon: WalletCards, count: "6" },
    { id: "intelligence", label: "Pazaryeri Analitiği", icon: BarChart3 },
  ]},
  { group: "PLATFORM", items: [
    { id: "integrations", label: "Entegrasyonlar", icon: Link2 },
    { id: "security", label: "Güven & Güvenlik", icon: ShieldCheck },
  ]},
] as const;

function MiniMap({ active = 3 }: { active?: number }) {
  const points = ["left-[16%] top-[32%]", "left-[35%] top-[55%]", "left-[55%] top-[24%]", "left-[68%] top-[62%]", "left-[83%] top-[38%]"];
  return <div className="relative min-h-64 overflow-hidden bg-muted/40">
    <div className="absolute inset-0 opacity-60" style={{ backgroundImage: "linear-gradient(var(--border) 1px, transparent 1px), linear-gradient(90deg, var(--border) 1px, transparent 1px)", backgroundSize: "36px 36px", transform: "rotate(-8deg) scale(1.2)" }} />
    <div className="absolute left-[7%] top-[50%] h-1 w-[82%] rotate-[-8deg] rounded-full bg-primary/30" />
    <div className="absolute left-[28%] top-[18%] h-[65%] w-1 rotate-[18deg] rounded-full bg-border" />
    {points.slice(0, active).map((point, i) => <div key={point} className={`absolute ${point} flex size-8 items-center justify-center rounded-full border-2 border-card bg-primary text-primary-foreground shadow-md`}><span className="text-[10px] font-bold">{i + 1}</span></div>)}
    <div className="absolute bottom-4 left-4 rounded-lg border bg-card/90 px-3 py-2 text-xs shadow-sm"><strong>Merter ağı</strong><span className="ml-2 text-muted-foreground">24 canlı iş · 18 kurye</span></div>
  </div>;
}

function DeliveryTable({ onSelect, limit }: { onSelect: (delivery: Delivery) => void; limit?: number }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left text-sm"><thead className="border-b bg-muted/35 text-[11px] font-semibold uppercase tracking-wide text-muted-foreground"><tr><th className="px-5 py-3">Teslimat</th><th className="px-4 py-3">Tekstil yükü</th><th className="px-4 py-3">Kurye</th><th className="px-4 py-3">Durum</th><th className="px-4 py-3">ETA</th><th className="px-4 py-3 text-right">Müşteri fiyatı</th></tr></thead><tbody>{deliveries.slice(0, limit).map(d => <tr key={d.id} onClick={() => onSelect(d)} className="cursor-pointer border-b last:border-0 hover:bg-muted/35"><td className="px-5 py-3.5"><div className="flex flex-col gap-1"><strong className="font-mono text-xs">{d.id}</strong><span className="text-xs text-muted-foreground">{d.route}</span></div></td><td className="px-4 py-3.5"><div className="flex flex-col gap-1"><strong className="text-xs">{d.cargo}</strong><span className="text-xs text-muted-foreground">{d.units} · {d.vehicle}</span></div></td><td className="px-4 py-3.5 text-xs">{d.courier}</td><td className="px-4 py-3.5"><StatusBadge status={d.status} /></td><td className={`px-4 py-3.5 text-xs font-semibold ${d.risk ? "text-destructive" : ""}`}>{d.eta}</td><td className="px-4 py-3.5 text-right font-mono text-xs font-semibold">{d.price}</td></tr>)}</tbody></table></div>;
}

function DispatchColumn({ title, count, tone, items }: { title: string; count: number; tone: "neutral" | "warning" | "danger" | "primary"; items: Delivery[] }) {
  return <div className="flex min-w-[260px] flex-1 flex-col gap-3"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><span className={`size-2 rounded-full ${tone === "danger" ? "bg-destructive" : tone === "warning" ? "bg-accent" : tone === "primary" ? "bg-primary" : "bg-muted-foreground"}`} /><h3 className="text-xs font-semibold">{title}</h3></div><Badge tone={tone}>{count}</Badge></div>{items.map(d => <Card key={`${title}-${d.id}`} className="p-3"><div className="flex flex-col gap-3"><div className="flex items-start justify-between gap-2"><div className="flex flex-col gap-1"><span className="font-mono text-[11px] text-muted-foreground">{d.id}</span><strong className="text-xs">{d.company}</strong></div>{d.risk && <Badge tone="danger">SLA</Badge>}</div><p className="text-xs leading-relaxed">{d.route}</p><div className="flex items-center justify-between gap-2 text-[11px] text-muted-foreground"><span>{d.cargo}</span><span className="font-semibold text-foreground">{d.eta}</span></div></div></Card>)}</div>;
}

function CommandCenter({ onSelect }: { onSelect: (d: Delivery) => void }) {
  const [assigned, setAssigned] = useState(false);
  return <div className="flex flex-col gap-5">
    <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex flex-col gap-1"><div className="flex items-center gap-2"><h1 className="text-balance text-2xl font-semibold tracking-tight">Operasyon Merkezi</h1><Badge tone="positive">CANLI</Badge></div><p className="text-sm text-muted-foreground">Merter tekstil ağının sevkiyat, eşleşme ve müdahale komuta merkezi.</p></div><div className="flex gap-2"><Button variant="outline"><Map />Harita görünümü</Button><Button><Plus />Yeni teslimat</Button></div></div>
    <div className="grid overflow-hidden rounded-xl border bg-card sm:grid-cols-2 xl:grid-cols-5"><Metric label="Canlı teslimat" value="24" change="+6 bugün" /><Metric label="Kurye bekleyen" value={assigned ? "3" : "4"} change="2 kritik" trend="down" /><Metric label="Geciken işler" value="3" change="%4,8 SLA" trend="down" /><Metric label="Aktif kurye" value="18" change="%76 kullanım" /><Metric label="Bugünkü hacim" value="₺86.4K" change="+%12,8" /></div>
    <div className="grid gap-5 xl:grid-cols-[1.45fr_.8fr]"><Card><CardHeader title="Canlı operasyon ağı" description="Kurye konumları, tekstil kümeleri ve terminal akışı" action={<Badge tone="primary">30 sn önce</Badge>} /><MiniMap active={5} /></Card><Card><CardHeader title="Müdahale kuyruğu" description="Operasyon ekibinin dikkatini bekleyen işler" /><div className="flex flex-col gap-1 p-2">{deliveries.filter(d => d.risk).map((d, i) => <button key={d.id} onClick={() => onSelect(d)} className="flex items-center justify-between gap-4 rounded-lg p-3 text-left hover:bg-muted"><span className={`flex size-9 items-center justify-center rounded-lg ${i === 0 ? "bg-destructive/12 text-destructive" : "bg-accent/14 text-accent"}`}>{i === 0 ? <Clock3 /> : <UserRoundCheck />}</span><span className="min-w-0 flex-1"><strong className="block truncate text-xs">{i === 0 ? "İhracat teslimatı gecikiyor" : "Manuel kurye ataması gerekli"}</strong><small className="text-muted-foreground">{d.id} · {d.route}</small></span><ChevronRight className="size-4 text-muted-foreground" /></button>)}</div></Card></div>
    <Card><CardHeader title="Canlı dispatch board" description="Eşleşme hunisi ve teslimat ilerlemesi" action={<Button variant="ghost">Tümünü aç <ArrowRight /></Button>} /><div className="flex gap-4 overflow-x-auto p-5"><DispatchColumn title="Talep Alındı" count={6} tone="neutral" items={[deliveries[1]]} /><DispatchColumn title="Kurye Aranıyor" count={assigned ? 3 : 4} tone="warning" items={assigned ? [] : [deliveries[1]]} /><DispatchColumn title="Alımda" count={5} tone="primary" items={[deliveries[2]]} /><DispatchColumn title="Yolda" count={9} tone="primary" items={[deliveries[0], deliveries[3]]} /></div></Card>
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Card><CardHeader title="Manuel kurye atama" description="CH-2840 · 12 rulo denim · Güngören → Ambarlı" action={<Badge tone="warning">18 dk kaldı</Badge>} /><div className="grid gap-4 p-5 md:grid-cols-3">{[{name:"Burak Yılmaz",v:"Kamyonet",r:"4,94",d:"1,8 km"},{name:"Özgür Demir",v:"Panelvan",r:"4,88",d:"2,4 km"},{name:"Ahmet Işık",v:"Kamyonet",r:"4,91",d:"3,1 km"}].map((c,i)=><button disabled={assigned} onClick={() => setAssigned(true)} key={c.name} className="flex flex-col gap-3 rounded-lg border p-4 text-left hover:border-primary disabled:opacity-50"><div className="flex items-center justify-between"><span className="flex size-9 items-center justify-center rounded-full bg-muted font-semibold">{c.name.split(" ").map(x=>x[0]).join("")}</span>{i===0&&<Badge tone="positive">En yakın</Badge>}</div><strong className="text-sm">{c.name}</strong><span className="text-xs text-muted-foreground">{c.v} · ★ {c.r} · {c.d}</span><span className="text-xs font-semibold text-primary">{assigned ? "Atandı" : "₺2.738 hakediş"}</span></button>)}</div></Card><Card><CardHeader title="Gelecek operasyon katmanı" description="AI özellikleri henüz devrede değil" /><div className="grid gap-3 p-5"><ComingSoon title="Akıllı Kurye Atama" description="Uygunluk, kapasite ve geçmiş performans ile eşleştirme." /><ComingSoon title="Gecikme Uyarıları" description="Risk oluşmadan operasyon ekibini uyaracak tahminler." /></div></Card></div>
  </div>;
}

function DeliveriesView({ onSelect }: { onSelect: (d: Delivery) => void }) {
  return <div className="flex flex-col gap-5"><PageTitle title="Canlı Teslimatlar" description="Tekstil sevkiyatlarının uçtan uca operasyon görünümü." action="Teslimat oluştur" /><Card><div className="flex flex-wrap items-center gap-3 border-b p-4"><div className="flex min-w-60 flex-1 items-center gap-2 rounded-lg border bg-background px-3"><Search className="size-4 text-muted-foreground" /><input aria-label="Teslimat ara" placeholder="ID, şirket, rota veya kurye ara" className="h-10 flex-1 bg-transparent text-sm outline-none" /></div><Button variant="outline"><SlidersHorizontal />Filtreler</Button><Button variant="outline"><FileText />Dışa aktar</Button></div><DeliveryTable onSelect={onSelect} /></Card></div>;
}

function PageTitle({ title, description, action }: { title: string; description: string; action?: string }) {
  return <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex flex-col gap-1"><h1 className="text-balance text-2xl font-semibold tracking-tight">{title}</h1><p className="text-sm text-muted-foreground">{description}</p></div>{action && <Button><Plus />{action}</Button>}</div>;
}

function CompanyView({ onSelect }: { onSelect: (d: Delivery) => void }) {
  const [created, setCreated] = useState(false);
  return <div className="flex flex-col gap-5"><PageTitle title="Mavi Çizgi Tekstil" description="Sevkiyat talebi, eşleşme ve faturalandırma çalışma alanı." action="Yeni sevkiyat" /><div className="grid overflow-hidden rounded-xl border bg-card sm:grid-cols-2 lg:grid-cols-4"><Metric label="Bu ay sevkiyat" value="86" change="+%14" /><Metric label="Yoldaki yük" value="12" change="3 terminal" /><Metric label="Aylık harcama" value="₺148.6K" change="+%8,2" /><Metric label="Zamanında teslimat" value="%96,4" change="+1,8 puan" /></div><div className="grid gap-5 xl:grid-cols-[1fr_.75fr]"><Card><CardHeader title="Tekstil sevkiyatı oluştur" description="Fiyat kuralı, kapasite ve hizmet gereksinimleri birlikte hesaplanır." /><div className="grid gap-4 p-5 md:grid-cols-2"><Field label="Alım noktası" value="Merter, Keresteciler Sitesi" /><Field label="Varış noktası" value="İkitelli OSB" /><Field label="Yük tipi" value="Hazır giyim kolisi" /><Field label="Miktar / ağırlık" value="24 koli · 286 kg" /><Field label="Hizmet seviyesi" value="Aynı Gün" /><Field label="Araç tipi" value="Panelvan" /><Field label="Elleçleme" value="Askılı taşıma · Kuru alan" /><Field label="Teslimat penceresi" value="Bugün, 14:00–16:00" /><div className="md:col-span-2 flex items-center justify-between rounded-lg bg-muted p-4"><div><span className="block text-xs text-muted-foreground">Kural bazlı müşteri fiyatı</span><strong className="text-xl">₺2.480</strong></div><Button onClick={() => setCreated(true)}>{created ? <Check /> : <PackageCheck />}{created ? "Talep oluşturuldu" : "Sevkiyat talebi oluştur"}</Button></div></div></Card><Card><CardHeader title="Fiyat dökümü" description="FR-128 · Merter–İkitelli Panelvan v4" /><div className="flex flex-col gap-3 p-5">{[["Rota taban fiyatı","₺1.850"],["286 kg kapasite","₺220"],["Askılı taşıma","₺180"],["Aynı gün hizmet","₺230"]].map(x=><div key={x[0]} className="flex justify-between gap-4 text-sm"><span className="text-muted-foreground">{x[0]}</span><strong>{x[1]}</strong></div>)}<div className="my-1 border-t" /><PriceRow label="Müşteri Fiyatı" value="₺2.480" /><PriceRow label="Kurye Kazancı" value="₺2.108" /><PriceRow label="Pazaryeri Komisyonu" value="₺372 · %15" /></div></Card></div><Card><CardHeader title="Şirket sevkiyatları" description="Canlı ve tamamlanan tekstil hareketleri" /><DeliveryTable onSelect={onSelect} limit={4} /></Card></div>;
}

function CourierView() {
  const [accepted, setAccepted] = useState(false);
  return <div className="flex flex-col gap-5"><PageTitle title="Kurye Pazaryeri" description="Yakındaki tekstil işleri, kapasite ve haftalık hakedişler." /><div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Card><CardHeader title="Yakındaki uygun işler" description="Kamyonet · 720 kg boş kapasite · Merter çevresi" action={<Badge tone="positive">MÜSAİT</Badge>} /><div className="grid gap-4 p-5 md:grid-cols-2">{deliveries.slice(0,4).map((d,i)=><div key={d.id} className="flex flex-col gap-4 rounded-lg border p-4"><div className="flex items-start justify-between gap-3"><div><span className="font-mono text-[11px] text-muted-foreground">{d.id}</span><h3 className="mt-1 text-sm font-semibold">{d.route}</h3></div><Badge tone={i===1?"warning":"primary"}>{d.service}</Badge></div><p className="text-xs leading-relaxed text-muted-foreground">{d.cargo}<br />{d.units} · {d.vehicle}</p><div className="flex items-end justify-between"><div><span className="block text-[11px] text-muted-foreground">Kurye kazancı</span><strong>{i===0?"₺2.108":i===1?"₺2.738":"₺968"}</strong></div><Button variant={i===0?"primary":"outline"} onClick={()=>i===0&&setAccepted(true)}>{i===0&&accepted?<Check />:<ArrowRight />}{i===0&&accepted?"Kabul edildi":"İşi incele"}</Button></div></div>)}</div></Card><div className="flex flex-col gap-5"><Card><CardHeader title="Bugünkü performans" /><div className="grid grid-cols-2"><Metric compact label="Tamamlanan" value="6" change="+2" /><Metric compact label="Kazanç" value="₺8.940" change="+%18" /><Metric compact label="Kabul oranı" value="%92" /><Metric compact label="Puan" value="4,94" /></div></Card><Card><CardHeader title="Güvenli teslimat" description="Teslimat kanıtı ve doğrulama" /><div className="flex flex-col gap-3 p-5"><Button variant="outline" className="justify-start"><QrCode />QR ile teslim al</Button><Button variant="outline" className="justify-start"><FileCheck2 />Teslimat kanıtı yükle</Button><Button variant="outline" className="justify-start"><MessageSquareText />Güvenli mesajlaşma</Button></div></Card></div></div></div>;
}

function PricingView() {
  const [simulated, setSimulated] = useState(false);
  return <div className="flex flex-col gap-5"><PageTitle title="Fiyatlandırma Motoru" description="AI kullanmadan, versiyonlu iş kurallarıyla müşteri fiyatı ve kurye hakedişi yönetin." action="Yeni fiyat kuralı" /><div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Card><CardHeader title="Aktif fiyat kuralları" description="Bölge, tekstil yükü, hizmet ve araç bazında önceliklendirilmiş kurallar" action={<Badge tone="positive">32 AKTİF</Badge>} /><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead className="border-b bg-muted/35 text-[11px] uppercase text-muted-foreground"><tr><th className="px-5 py-3">Kural</th><th className="px-4 py-3">Koşullar</th><th className="px-4 py-3">Minimum</th><th className="px-4 py-3">Komisyon</th><th className="px-4 py-3">Durum</th></tr></thead><tbody>{priceRules.map(r=><tr key={r.name} className="border-b last:border-0"><td className="px-5 py-4 text-xs font-semibold">{r.name}</td><td className="px-4 py-4 text-xs text-muted-foreground">{r.conditions}</td><td className="px-4 py-4 font-mono text-xs">{r.minimum}</td><td className="px-4 py-4 font-mono text-xs">{r.commission}</td><td className="px-4 py-4"><StatusBadge status={r.status} /></td></tr>)}</tbody></table></div></Card><Card><CardHeader title="Kural simülatörü" description="Yayınlamadan önce fiyat bileşimini doğrulayın." /><div className="flex flex-col gap-4 p-5"><Field label="Rota" value="Merter → İkitelli" /><Field label="Yük" value="24 koli hazır giyim · 286 kg" /><Field label="Hizmet / Araç" value="Aynı Gün · Panelvan" /><Button onClick={()=>setSimulated(true)}><Gauge />Fiyatı simüle et</Button>{simulated&&<div className="flex flex-col gap-2 rounded-lg bg-muted p-4"><PriceRow label="Müşteri Fiyatı" value="₺2.480" /><PriceRow label="Kurye Kazancı" value="₺2.108" /><PriceRow label="Komisyon" value="₺372" /><span className="mt-1 text-[11px] text-muted-foreground">FR-128 v4 kuralı eşleşti · minimum fiyat uygulanmadı.</span></div>}</div></Card></div><Card><CardHeader title="Kural parametreleri" description="Motorun değerlendirdiği yapılandırılabilir iş girdileri" /><div className="flex flex-wrap gap-2 p-5">{["Alım ilçesi","Varış ilçesi","Yük tipi","Miktar","Ağırlık","Hacim","Aciliyet","Elleçleme","Hizmet seviyesi","Kurye aracı","Minimum fiyat","Komisyon","Kurye hakedişi"].map(x=><Badge key={x} tone="neutral">{x}</Badge>)}</div></Card></div>;
}

function FinanceView() {
  return <div className="flex flex-col gap-5"><PageTitle title="Finans & Mutabakat" description="Şirket bakiyeleri, kurye hakedişleri ve pazaryeri komisyonunun tek görünümü." action="Mutabakat oluştur" /><div className="grid overflow-hidden rounded-xl border bg-card sm:grid-cols-2 xl:grid-cols-4"><Metric label="Bekleyen tahsilat" value="₺284.6K" change="18 fatura" trend="down" /><Metric label="Kurye ödemeleri" value="₺168.2K" change="Cuma günü" /><Metric label="Bu ay komisyon" value="₺94.8K" change="+%15,4" /><Metric label="Mutabakat farkı" value="₺1.240" change="6 kayıt" trend="down" /></div><div className="grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><Card><CardHeader title="İşlem geçmişi" description="Teslimat, ödeme ve haftalık mutabakat hareketleri" action={<Button variant="outline"><FileText />Rapor al</Button>} /><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="border-b bg-muted/35 uppercase text-muted-foreground"><tr><th className="px-5 py-3">İşlem</th><th className="px-4 py-3">Taraf</th><th className="px-4 py-3">Tür</th><th className="px-4 py-3">Tarih</th><th className="px-4 py-3">Tutar</th><th className="px-4 py-3">Durum</th></tr></thead><tbody>{transactions.map(t=><tr key={t.id} className="border-b last:border-0"><td className="px-5 py-4 font-mono">{t.id}</td><td className="px-4 py-4 font-semibold">{t.party}</td><td className="px-4 py-4 text-muted-foreground">{t.kind}</td><td className="px-4 py-4 text-muted-foreground">{t.date}</td><td className="px-4 py-4 font-mono font-semibold">{t.amount}</td><td className="px-4 py-4"><StatusBadge status={t.status} /></td></tr>)}</tbody></table></div></Card><Card><CardHeader title="Haftalık mutabakat" description="15–21 Temmuz dönemi" /><div className="flex flex-col gap-4 p-5"><PriceRow label="Şirket tahsilatları" value="₺486.820" /><PriceRow label="Kurye hakedişleri" value="₺405.140" /><PriceRow label="Pazaryeri komisyonu" value="₺78.960" /><PriceRow label="Düzeltmeler" value="₺2.720" /><div className="border-t" /><PriceRow label="Net pozisyon" value="₺78.960" /><Button><HandCoins />Mutabakatı incele</Button></div></Card></div></div>;
}

function IntelligenceView() {
  return <div className="flex flex-col gap-5"><PageTitle title="Pazaryeri Analitiği" description="Tekstil lojistik ağının arz, talep, bağlılık ve yoğunluk sağlığı." /><div className="grid overflow-hidden rounded-xl border bg-card sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{intelligence.map((m,i)=><Metric key={m.label} compact label={m.label} value={m.value} change={m.change} trend={i===2?"flat":"up"} />)}</div><div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Card><CardHeader title="Pazaryeri büyümesi" description="Son 12 ay · tamamlanan tekstil sevkiyatları" action={<Badge tone="positive">+%28,6 Y/Y</Badge>} /><div className="flex h-72 items-end gap-3 p-6">{[32,39,35,48,52,58,62,71,68,79,86,94].map((v,i)=><div key={i} className="group flex h-full flex-1 items-end"><div className="w-full rounded-t bg-primary/75 transition group-hover:bg-primary" style={{height:`${v}%`}} /></div>)}</div></Card><Card><CardHeader title="Ağ yoğunluğu" description="En aktif tekstil koridorları" /><div className="flex flex-col gap-4 p-5">{[["Merter → İkitelli","842 iş","%92"],["Güngören → Ambarlı","618 iş","%74"],["Zeytinburnu → İGA","486 iş","%61"],["Merter → Laleli","392 iş","%52"]].map(x=><div key={x[0]} className="flex flex-col gap-2"><div className="flex justify-between text-xs"><strong>{x[0]}</strong><span className="text-muted-foreground">{x[1]}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:x[2]}} /></div></div>)}</div></Card></div><div className="grid gap-5 md:grid-cols-3"><ComingSoon title="Lojistik İçgörüleri" description="Ağ davranışındaki değişimleri açıklayan otomatik içgörüler." /><ComingSoon title="ETA Tahmini" description="Rota, terminal ve zaman penceresine göre dinamik varış tahmini." /><ComingSoon title="Fiyat Önerisi" description="Mevcut kural motoruna alternatif fiyat önerileri." /></div></div>;
}

function IntegrationsView() {
  const integrations = [{name:"Logo ERP",type:"ERP sistemi",state:"Bağlı",icon:Layers3},{name:"Paraşüt",type:"Muhasebe",state:"Bağlı",icon:CircleDollarSign},{name:"WhatsApp Business",type:"İletişim",state:"Kurulum gerekli",icon:MessageSquareText},{name:"Shopify",type:"E-ticaret",state:"Yakında",icon:Boxes},{name:"Kargo şirketleri",type:"Terminal ağı",state:"Yakında",icon:Truck},{name:"REST API",type:"Geliştirici",state:"Aktif",icon:Webhook}];
  return <div className="flex flex-col gap-5"><PageTitle title="Entegrasyonlar & API" description="CarryHub iş akışlarını ERP, muhasebe, iletişim ve mobil kanallara bağlayın." /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{integrations.map(i=><Card key={i.name} className="p-5"><div className="flex items-start justify-between gap-4"><span className="flex size-10 items-center justify-center rounded-lg bg-muted"><i.icon className="size-5" /></span><Badge tone={i.state==="Bağlı"||i.state==="Aktif"?"positive":i.state==="Yakında"?"neutral":"warning"}>{i.state}</Badge></div><div className="mt-5 flex flex-col gap-1"><h3 className="text-sm font-semibold">{i.name}</h3><p className="text-xs text-muted-foreground">{i.type}</p></div><Button disabled={i.state==="Yakında"} variant="outline" className="mt-5 w-full">Yapılandır <ArrowRight /></Button></Card>)}</div><Card><CardHeader title="Webhook olayları" description="Teslimat ve finans durumlarını kendi sistemlerinize aktarın." action={<Button variant="outline"><Plus />Endpoint ekle</Button>} /><div className="grid gap-3 p-5 md:grid-cols-3">{["delivery.status_changed","courier.assigned","settlement.completed"].map((e,i)=><div key={e} className="rounded-lg border p-4"><div className="flex items-center justify-between"><code className="text-xs font-semibold">{e}</code><Badge tone={i===2?"warning":"positive"}>{i===2?"Bekliyor":"200 OK"}</Badge></div><p className="mt-2 text-[11px] text-muted-foreground">Son çağrı: {i+2} dk önce · 148 ms</p></div>)}</div></Card></div>;
}

function SecurityView() {
  return <div className="flex flex-col gap-5"><PageTitle title="Güven, Doğrulama & Yetkiler" description="Pazaryeri iletişimi, teslimat kanıtı ve değişiklik izlerinin yönetimi." /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[{t:"Maskeli iletişim",d:"Telefon numaraları taraflar arasında gizli.",i:KeyRound},{t:"Güvenli mesajlaşma",d:"Teslimata bağlı kayıtlı görüşmeler.",i:MessageSquareText},{t:"QR doğrulama",d:"Alım ve teslimde tekil kod kontrolü.",i:QrCode},{t:"Dijital imza",d:"Teslim alan kişi ve zaman damgası.",i:FileCheck2}].map(x=><Card key={x.t} className="p-5"><x.i className="size-5 text-primary" /><h3 className="mt-4 text-sm font-semibold">{x.t}</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{x.d}</p><Badge tone="positive">Hazır</Badge></Card>)}</div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card><CardHeader title="Denetim izi" description="Kritik operasyon ve finans değişiklikleri" /><div className="flex flex-col">{[{a:"Ayşe K.",e:"CH-2840 kurye atamasını değiştirdi",t:"13:42 · Operasyon"},{a:"Sistem",e:"FR-128 v4 fiyat kuralını uyguladı",t:"13:39 · Pricing Engine"},{a:"Mehmet D.",e:"Nora Export faturasını onayladı",t:"12:18 · Finans"},{a:"Selin A.",e:"CH-2838 teslimat kanıtı yükledi",t:"11:54 · Mobil"}].map(x=><div key={x.e} className="flex gap-3 border-b p-4 last:border-0"><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-muted text-[10px] font-semibold">{x.a.slice(0,2)}</span><div><p className="text-xs font-semibold">{x.e}</p><small className="text-muted-foreground">{x.a} · {x.t}</small></div></div>)}</div></Card><Card><CardHeader title="Rol yetkileri" description="En az yetki prensibi" /><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="border-b text-muted-foreground"><tr><th className="p-3 text-left">Kaynak</th><th>Ops</th><th>Finans</th><th>Şirket</th></tr></thead><tbody>{[["Kurye atama",1,0,0],["Fiyat kuralları",1,0,0],["Mutabakat",0,1,0],["Teslimat oluştur",1,0,1],["Denetim izi",1,1,0]].map(r=><tr key={String(r[0])} className="border-b last:border-0"><td className="p-3 font-medium">{r[0]}</td>{r.slice(1).map((v,i)=><td key={i} className="text-center">{v?<Check className="mx-auto size-4 text-primary" />:<span className="text-muted-foreground">—</span>}</td>)}</tr>)}</tbody></table></div></Card></div></div>;
}

function Field({ label, value }: { label: string; value: string }) { return <label className="flex flex-col gap-1.5 text-xs font-medium"><span className="text-muted-foreground">{label}</span><input defaultValue={value} className="h-10 rounded-lg border bg-background px-3 text-sm outline-none focus:border-primary" /></label>; }
function PriceRow({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-4"><strong className="text-xs">{label}</strong><strong className="font-mono text-sm">{value}</strong></div>; }

function DeliveryDrawer({ delivery, close }: { delivery: Delivery; close: () => void }) {
  return <div className="fixed inset-0 z-50 flex justify-end bg-foreground/30" onClick={close}><aside onClick={e=>e.stopPropagation()} className="h-full w-full max-w-xl overflow-y-auto border-l bg-background shadow-2xl"><div className="sticky top-0 flex items-center justify-between border-b bg-background/95 p-5"><div><span className="font-mono text-xs text-muted-foreground">{delivery.id}</span><h2 className="text-lg font-semibold">{delivery.route}</h2></div><Button variant="ghost" onClick={close}><X /></Button></div><div className="flex flex-col gap-5 p-5"><div className="flex items-center justify-between"><StatusBadge status={delivery.status} /><span className="text-xs font-semibold">ETA {delivery.eta}</span></div><MiniMap active={3} /><Card><CardHeader title="Tekstil yükü" /><div className="grid gap-4 p-5 sm:grid-cols-2"><Info label="Şirket" value={delivery.company} /><Info label="Yük" value={delivery.cargo} /><Info label="Kapasite" value={delivery.units} /><Info label="Araç" value={delivery.vehicle} /><Info label="Hizmet" value={delivery.service} /><Info label="Kurye" value={delivery.courier} /></div></Card><Card><CardHeader title="Fiyat özeti" description="Uygulanan kural: FR-128 v4" /><div className="flex flex-col gap-3 p-5"><PriceRow label="Müşteri Fiyatı" value={delivery.price} /><PriceRow label="Kurye Kazancı" value={delivery.id==="CH-2840"?"₺2.738":"₺2.108"} /><PriceRow label="Pazaryeri Komisyonu" value={delivery.id==="CH-2840"?"₺522 · %16":"₺372 · %15"} /><Button variant="outline">Fiyat dökümünü aç <ChevronDown /></Button></div></Card><Card><CardHeader title="Teslimat güvenliği" /><div className="grid gap-3 p-5 sm:grid-cols-2"><Button variant="outline"><MessageSquareText />Maskeli mesaj</Button><Button variant="outline"><QrCode />QR doğrulama</Button><Button variant="outline"><FileCheck2 />Teslimat kanıtı</Button><Button variant="outline"><History />Aktivite kaydı</Button></div></Card></div></aside></div>;
}
function Info({ label, value }: { label: string; value: string }) { return <div><span className="block text-[11px] text-muted-foreground">{label}</span><strong className="text-xs">{value}</strong></div>; }

export default function CarryHubApp() {
  const [view, setView] = useState<View>("command");
  const [role, setRole] = useState<Role>("Operasyon");
  const [sidebar, setSidebar] = useState(false);
  const [selected, setSelected] = useState<Delivery | null>(null);
  const [notifications, setNotifications] = useState(false);
  const currentLabel = useMemo(() => {
    for (const group of nav) {
      const item = group.items.find((entry) => entry.id === view);
      if (item) return item.label;
    }
    return "CarryHub";
  }, [view]);
  const changeRole = (r: Role) => { setRole(r); setView(roleViews[r]); };
  return <main className="min-h-screen bg-background text-foreground"><div className="flex min-h-screen">
    {sidebar && <button aria-label="Menüyü kapat" onClick={() => setSidebar(false)} className="fixed inset-0 z-30 bg-foreground/30 lg:hidden" />}
    <aside className={`${sidebar ? "w-64 translate-x-0" : "w-64 -translate-x-full"} fixed inset-y-0 left-0 z-40 overflow-hidden border-r bg-card transition-transform lg:sticky lg:w-64 lg:translate-x-0`}><div className="flex h-16 items-center gap-3 border-b px-5"><span className="flex size-9 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Route className="size-5" /></span><div><strong className="block text-sm tracking-tight">CarryHub</strong><span className="text-[10px] font-medium text-muted-foreground">TEKSTİL LOJİSTİK AĞI</span></div></div><nav className="scrollbar-none flex h-[calc(100vh-8rem)] flex-col gap-6 overflow-y-auto p-3">{nav.map(group=><div key={group.group} className="flex flex-col gap-1"><span className="px-3 py-1 text-[10px] font-semibold tracking-widest text-muted-foreground">{group.group}</span>{group.items.map(item=><button key={item.id} onClick={()=>{setView(item.id); if(innerWidth<1024)setSidebar(false)}} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-xs font-medium transition ${view===item.id?"bg-primary text-primary-foreground":"text-muted-foreground hover:bg-muted hover:text-foreground"}`}><item.icon className="size-4" /><span className="flex-1">{item.label}</span>{"count" in item&&item.count&&<span className={`rounded px-1.5 py-0.5 text-[10px] ${view===item.id?"bg-primary-foreground/15":"bg-muted"}`}>{item.count}</span>}</button>)}</div>)}</nav><div className="absolute bottom-0 left-0 right-0 border-t bg-card p-3"><button className="flex w-full items-center gap-3 rounded-lg p-2 hover:bg-muted"><span className="flex size-8 items-center justify-center rounded-full bg-primary/12 text-xs font-semibold text-primary">AK</span><span className="min-w-0 flex-1 text-left"><strong className="block truncate text-xs">Ayşe Karaca</strong><small className="text-muted-foreground">Merter Operasyon</small></span><Settings2 className="size-4 text-muted-foreground" /></button></div></aside>
    <div className="min-w-0 flex-1"><header className="sticky top-0 z-30 flex h-16 items-center justify-between gap-3 border-b bg-background/90 px-4 backdrop-blur md:px-6"><div className="flex items-center gap-3"><button aria-label="Menüyü aç" onClick={()=>setSidebar(!sidebar)} className="flex size-9 items-center justify-center rounded-lg border bg-card"><Menu className="size-4" /></button><div className="hidden items-center gap-2 text-xs sm:flex"><span className="text-muted-foreground">CarryHub</span><ChevronRight className="size-3 text-muted-foreground" /><strong>{currentLabel}</strong></div></div><div className="flex items-center gap-2"><div className="relative"><button onClick={()=>setNotifications(!notifications)} aria-label="Bildirimler" className="relative flex size-9 items-center justify-center rounded-lg border bg-card"><Bell className="size-4" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-destructive" /></button>{notifications&&<Card className="absolute right-0 top-12 w-80 p-2 shadow-xl"><div className="p-3"><strong className="text-sm">Operasyon bildirimleri</strong></div><div className="rounded-lg bg-muted p-3 text-xs">CH-2838 teslimatı 18 dakika gecikiyor.</div><div className="mt-1 rounded-lg p-3 text-xs">CH-2840 için manuel atama bekleniyor.</div></Card>}</div><div className="relative group"><button className="flex h-9 items-center gap-2 rounded-lg border bg-card px-3 text-xs font-semibold"><Grid2X2 className="size-4 text-primary" />{role}<ChevronDown className="size-3" /></button><div className="invisible absolute right-0 top-10 w-44 rounded-lg border bg-card p-1 opacity-0 shadow-xl transition group-hover:visible group-hover:opacity-100">{(["Operasyon","Şirket","Kurye","Yönetici"] as Role[]).map(r=><button key={r} onClick={()=>changeRole(r)} className="flex w-full items-center justify-between rounded-md px-3 py-2 text-xs hover:bg-muted">{r}{role===r&&<Check className="size-3 text-primary" />}</button>)}</div></div></div></header><div className="p-4 md:p-6 lg:p-8">{view==="command"&&<CommandCenter onSelect={setSelected} />}{view==="deliveries"&&<DeliveriesView onSelect={setSelected} />}{view==="company"&&<CompanyView onSelect={setSelected} />}{view==="courier"&&<CourierView />}{view==="pricing"&&<PricingView />}{view==="finance"&&<FinanceView />}{view==="intelligence"&&<IntelligenceView />}{view==="integrations"&&<IntegrationsView />}{view==="security"&&<SecurityView />}</div></div>
  </div>{selected&&<DeliveryDrawer delivery={selected} close={()=>setSelected(null)} />}</main>;
}
